version: '3.8'

services:
    postgres:
      container_name: pg_container
      image: postgres
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: directus
      volumes:
         - postgres:/data/postgres
      ports:
        - "5432:5432"
      restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped


volumes:
    postgres:
    pgadmin: